type Env = { DB: D1Database; SESSION_SECRET: string; ADMIN_BOOTSTRAP_SECRET: string; ALLOWED_ORIGINS: string };
type User = { id:string; name:string; email:string; role:'user'|'admin'; status:string; access_until:string|null; internal_note:string|null; last_activity_at:string|null; created_at:string };
const json = (data:unknown, status=200, headers:HeadersInit={}) => Response.json(data, { status, headers });
const now = () => new Date().toISOString();
const id = () => crypto.randomUUID();
const randomToken = () => { const bytes = new Uint8Array(32); crypto.getRandomValues(bytes); return btoa(String.fromCharCode(...bytes)).replaceAll('+','-').replaceAll('/','_').replaceAll('=',''); };
const text = (v:unknown) => typeof v === 'string' ? v.trim() : '';
const cents = (v:unknown) => { const n = Number(v); return Number.isFinite(n) && n >= 0 ? Math.round(n * 100) : -1; };
const date = (v:unknown) => /^\d{4}-\d{2}-\d{2}$/.test(text(v)) ? text(v) : '';

async function digest(value:string) { return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256', new TextEncoder().encode(value)))).map(x=>x.toString(16).padStart(2,'0')).join(''); }
async function passwordHash(password:string) {
  const salt = randomToken().slice(0, 32);
  const key = await crypto.subtle.importKey('raw', new TextEncoder().encode(password), 'PBKDF2', false, ['deriveBits']);
  const bits = await crypto.subtle.deriveBits({name:'PBKDF2', salt:new TextEncoder().encode(salt), iterations:100000, hash:'SHA-256'}, key, 256);
  return `pbkdf2$100000$${salt}$${Array.from(new Uint8Array(bits)).map(x=>x.toString(16).padStart(2,'0')).join('')}`;
}
async function passwordOk(password:string, stored:string) {
  const [, iteration, salt, expected] = stored.split('$');
  if (!iteration || !salt || !expected) return false;
  const key = await crypto.subtle.importKey('raw', new TextEncoder().encode(password), 'PBKDF2', false, ['deriveBits']);
  const bits = await crypto.subtle.deriveBits({name:'PBKDF2', salt:new TextEncoder().encode(salt), iterations:Number(iteration), hash:'SHA-256'}, key, 256);
  return await digest(Array.from(new Uint8Array(bits)).map(x=>x.toString(16).padStart(2,'0')).join('')) === await digest(expected);
}
function originAllowed(request:Request, env:Env) { const origin=request.headers.get('Origin'); return !origin || env.ALLOWED_ORIGINS.split(',').map(x=>x.trim()).includes(origin); }
function cors(request:Request, env:Env) { const origin=request.headers.get('Origin') || ''; return { 'Access-Control-Allow-Origin': origin && env.ALLOWED_ORIGINS.split(',').map(x=>x.trim()).includes(origin) ? origin : env.ALLOWED_ORIGINS.split(',')[0], 'Access-Control-Allow-Headers':'Authorization, Content-Type', 'Access-Control-Allow-Methods':'GET, POST, PUT, DELETE, OPTIONS', 'Vary':'Origin' }; }
async function body(request:Request) { try { return await request.json() as Record<string,unknown>; } catch { return {}; } }
async function auth(request:Request, env:Env):Promise<User|null> {
  const token=request.headers.get('Authorization')?.replace(/^Bearer\s+/i,''); if (!token) return null;
  const row=await env.DB.prepare('SELECT u.* FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>?').bind(await digest(token), now()).first<User>();
  if (row) await env.DB.prepare('UPDATE users SET last_activity_at=? WHERE id=?').bind(now(),row.id).run();
  return row;
}
function access(user:User, write=false) { if (user.role==='admin' || user.status==='admin') return true; const active=user.status==='active' && !!user.access_until && user.access_until>now(); return write ? active : ['active','expired','pending'].includes(user.status) || active; }
function invalid(condition:boolean,message:string) { return condition ? json({error:message},400) : null; }
function month(v=new Date()) { return v.toISOString().slice(0,7); }

async function handle(request:Request, env:Env):Promise<Response> {
  const url=new URL(request.url), path=url.pathname.replace(/\/$/,'') || '/', method=request.method;
  if (method==='OPTIONS') return new Response(null,{status:204,headers:cors(request,env)});
  if (!originAllowed(request,env)) return json({error:'Origin nije dopušten.'},403,cors(request,env));
  if (path==='/health') return json({ok:true,service:'flipd-api',time:now()},200,cors(request,env));
  if (path==='/auth/register' && method==='POST') { const b=await body(request), name=text(b.name), email=text(b.email).toLowerCase(), password=text(b.password); const bad=invalid(!name||!email.includes('@')||password.length<8,'Ime, valjan e-mail i lozinka od najmanje 8 znakova su obavezni.'); if(bad)return bad; if(await env.DB.prepare('SELECT id FROM users WHERE email=?').bind(email).first())return json({error:'E-mail je već registriran.'},409); const userId=id(); await env.DB.prepare('INSERT INTO users(id,name,email,password_hash,status) VALUES(?,?,?,?,?)').bind(userId,name,email,await passwordHash(password),'pending').run(); return json({user:{id:userId,name,email,status:'pending'},message:'Račun je kreiran. Čeka odobrenje pristupa.'},201,cors(request,env)); }
  if (path==='/auth/login' && method==='POST') { const b=await body(request), email=text(b.email).toLowerCase(), password=text(b.password), row=await env.DB.prepare('SELECT * FROM users WHERE email=?').bind(email).first<User & {password_hash:string}>(); if(!row||!(await passwordOk(password,row.password_hash)))return json({error:'Neispravan e-mail ili lozinka.'},401,cors(request,env)); const token=randomToken(); await env.DB.prepare('INSERT INTO sessions(id,user_id,token_hash,expires_at) VALUES(?,?,?,?)').bind(id(),row.id,await digest(token),new Date(Date.now()+1000*60*60*24*30).toISOString()).run(); return json({token,user:{...row,password_hash:undefined},readOnly:!access(row,true)},200,cors(request,env)); }
  if (path==='/auth/logout' && method==='POST') { const token=request.headers.get('Authorization')?.replace(/^Bearer\s+/i,''); if(token)await env.DB.prepare('DELETE FROM sessions WHERE token_hash=?').bind(await digest(token)).run(); return json({ok:true},200,cors(request,env)); }
  if (path==='/auth/me' && method==='GET') { const user=await auth(request,env); if(!user)return json({error:'Niste prijavljeni.'},401,cors(request,env)); if(user.status==='active'&&user.access_until&&user.access_until<=now()) { await env.DB.prepare("UPDATE users SET status='expired' WHERE id=? AND role='user'").bind(user.id).run(); user.status='expired'; } return json({user,readOnly:!access(user,true)},200,cors(request,env)); }
  if(path==='/admin/bootstrap'&&method==='POST'){const b=await body(request);if(text(b.secret)!==env.ADMIN_BOOTSTRAP_SECRET)return json({error:'Neispravna bootstrap tajna.'},403,cors(request,env));const admin=await env.DB.prepare("SELECT id FROM users WHERE role='admin' LIMIT 1").first();if(admin)return json({error:'Admin već postoji.'},409,cors(request,env));const name=text(b.name),email=text(b.email).toLowerCase(),password=text(b.password);if(!name||!email||password.length<12)return json({error:'Admin podaci nisu valjani.'},400,cors(request,env));const adminId=id();await env.DB.prepare("INSERT INTO users(id,name,email,password_hash,role,status) VALUES(?,?,?,?, 'admin','admin')").bind(adminId,name,email,await passwordHash(password)).run();return json({ok:true},201,cors(request,env));}
  const user=await auth(request,env); if(!user)return json({error:'Potrebna je prijava.'},401,cors(request,env));
  if(path.startsWith('/admin/')) { if(user.role!=='admin')return json({error:'Samo admin može pristupiti.'},403,cors(request,env)); if(path==='/admin/users'&&method==='GET'){const rows=await env.DB.prepare('SELECT id,name,email,role,status,access_until,internal_note,last_activity_at,created_at FROM users ORDER BY created_at DESC').all();return json({users:rows.results},200,cors(request,env));} const m=path.match(/^\/admin\/users\/([^/]+)$/); if(m&&method==='PUT'){const b=await body(request), target=m[1], action=text(b.action);const u=await env.DB.prepare('SELECT * FROM users WHERE id=?').bind(target).first<User>();if(!u)return json({error:'Korisnik nije pronađen.'},404,cors(request,env));let status=u.status,until=u.access_until;if(action==='approve'||action==='extend'){const base=until&&until>now()?new Date(until):new Date();if(action==='approve'&&!until)base.setTime(Date.now());base.setMonth(base.getMonth()+1);until=base.toISOString();status='active';await env.DB.prepare('INSERT INTO access_periods(id,user_id,starts_at,ends_at,approved_by,note) VALUES(?,?,?,?,?,?)').bind(id(),target,now(),until,user.id,text(b.note)||null).run();}else if(action==='block'){status='blocked';}else if(action==='reactivate'){status='active';if(!until||until<=now()){const d=new Date();d.setMonth(d.getMonth()+1);until=d.toISOString();}}else if(action==='set_expiry'){until=new Date(text(b.access_until)).toISOString();status=until>now()?'active':'expired';await env.DB.prepare('INSERT INTO access_periods(id,user_id,starts_at,ends_at,approved_by,note) VALUES(?,?,?,?,?,?)').bind(id(),target,now(),until,user.id,text(b.note)||null).run();}else if(action==='note'){await env.DB.prepare('UPDATE users SET internal_note=? WHERE id=?').bind(text(b.note)||null,target).run();return json({ok:true},200,cors(request,env));}else return json({error:'Nepoznata admin akcija.'},400,cors(request,env));await env.DB.prepare('UPDATE users SET status=?,access_until=?,internal_note=COALESCE(?,internal_note) WHERE id=?').bind(status,until,text(b.note)||null,target).run();return json({ok:true},200,cors(request,env));}}
  if(!access(user,false))return json({error:'Račun nema pristup.'},403,cors(request,env));
  if(path==='/dashboard'&&method==='GET'){const m=url.searchParams.get('month')||month();const stats=await env.DB.prepare("SELECT COALESCE(SUM((sale_price_cents-cost_cents)*quantity),0) profit, COALESCE(SUM(quantity),0) sold FROM sales WHERE user_id=? AND substr(sold_on,1,7)=?").bind(user.id,m).first();const goal=await env.DB.prepare('SELECT amount_cents FROM monthly_goals WHERE user_id=? AND month=?').bind(user.id,m).first();const recent=await env.DB.prepare('SELECT s.*,p.name product_name,i.size_or_variant,c.name customer_name FROM sales s JOIN inventory_items i ON i.id=s.inventory_item_id JOIN products p ON p.id=i.product_id LEFT JOIN customers c ON c.id=s.customer_id WHERE s.user_id=? ORDER BY s.sold_on DESC,s.created_at DESC LIMIT 5').bind(user.id).all();return json({month:m,profitCents:Number(stats?.profit||0),sold:Number(stats?.sold||0),goalCents:Number((goal as {amount_cents?:number}|null)?.amount_cents||0),recent:recent.results,readOnly:!access(user,true)},200,cors(request,env));}
  if(path==='/goals'&&method==='PUT'){if(!access(user,true))return json({error:'Read-only način rada.'},403,cors(request,env));const b=await body(request), m=text(b.month)||month(), amount=cents(b.amount);if(amount<0)return json({error:'Cilj nije valjan.'},400,cors(request,env));await env.DB.prepare('INSERT INTO monthly_goals(user_id,month,amount_cents) VALUES(?,?,?) ON CONFLICT(user_id,month) DO UPDATE SET amount_cents=excluded.amount_cents').bind(user.id,m,amount).run();return json({ok:true},200,cors(request,env));}
  if(path==='/products'&&method==='GET'){const rows=await env.DB.prepare('SELECT * FROM products WHERE user_id=? ORDER BY name').bind(user.id).all();return json({products:rows.results},200,cors(request,env));}
  if(path==='/products'&&method==='POST'){if(!access(user,true))return json({error:'Read-only način rada.'},403,cors(request,env));const b=await body(request),name=text(b.name),category=text(b.category);if(!name||!['Obuća','Odjeća','Dodaci','Ostalo'].includes(category))return json({error:'Naziv i kategorija su obavezni.'},400,cors(request,env));const productId=id();await env.DB.prepare('INSERT INTO products(id,user_id,name,category,brand,model,note) VALUES(?,?,?,?,?,?,?)').bind(productId,user.id,name,category,text(b.brand)||null,text(b.model)||null,text(b.note)||null).run();return json({id:productId},201,cors(request,env));}
  if(path==='/inventory'&&method==='GET'){const rows=await env.DB.prepare('SELECT i.*,p.name product_name,p.category,p.brand FROM inventory_items i JOIN products p ON p.id=i.product_id WHERE i.user_id=? AND i.quantity>0 ORDER BY i.created_at DESC').bind(user.id).all();return json({items:rows.results},200,cors(request,env));}
  if(path==='/inventory'&&method==='POST'){if(!access(user,true))return json({error:'Read-only način rada.'},403,cors(request,env));const b=await body(request), productId=text(b.product_id),qty=Number(b.quantity||1),cost=cents(b.cost),purchased=date(b.purchased_on)||new Date().toISOString().slice(0,10);if(!productId||!Number.isInteger(qty)||qty<1||cost<0)return json({error:'Artikl, količina i nabavna cijena su obavezni.'},400,cors(request,env));const product=await env.DB.prepare('SELECT id FROM products WHERE id=? AND user_id=?').bind(productId,user.id).first();if(!product)return json({error:'Artikl nije pronađen.'},404,cors(request,env));const inventoryId=id();await env.DB.prepare('INSERT INTO inventory_items(id,user_id,product_id,quantity,original_quantity,cost_cents,purchased_on,status,size_or_variant,condition,note) VALUES(?,?,?,?,?,?,?,?,?,?,?)').bind(inventoryId,user.id,productId,qty,qty,cost,purchased,'available',text(b.size_or_variant)||null,text(b.condition)||'Novo',text(b.note)||null).run();return json({id:inventoryId},201,cors(request,env));}
  if(path==='/customers'&&method==='GET'){const rows=await env.DB.prepare('SELECT * FROM customers WHERE user_id=? ORDER BY name').bind(user.id).all();return json({customers:rows.results},200,cors(request,env));}
  if(path==='/customers'&&(method==='POST'||method==='PUT')){if(!access(user,true))return json({error:'Read-only način rada.'},403,cors(request,env));const b=await body(request),name=text(b.name),customerId=text(b.id)||id();if(!name)return json({error:'Ime kupca je obavezno.'},400,cors(request,env));if(method==='POST')await env.DB.prepare('INSERT INTO customers(id,user_id,name,phone,email,social,city_country,address,note) VALUES(?,?,?,?,?,?,?,?,?)').bind(customerId,user.id,name,text(b.phone)||null,text(b.email)||null,text(b.social)||null,text(b.city_country)||null,text(b.address)||null,text(b.note)||null).run();else await env.DB.prepare('UPDATE customers SET name=?,phone=?,email=?,social=?,city_country=?,address=?,note=? WHERE id=? AND user_id=?').bind(name,text(b.phone)||null,text(b.email)||null,text(b.social)||null,text(b.city_country)||null,text(b.address)||null,text(b.note)||null,customerId,user.id).run();return json({id:customerId},200,cors(request,env));}
  if(path.startsWith('/customers/')&&method==='DELETE'){if(!access(user,true))return json({error:'Read-only način rada.'},403,cors(request,env));await env.DB.prepare('DELETE FROM customers WHERE id=? AND user_id=?').bind(path.split('/')[2],user.id).run();return json({ok:true},200,cors(request,env));}
  if(path==='/sales'&&method==='GET'){let q='SELECT s.*,p.name product_name,i.size_or_variant,c.name customer_name,p.category FROM sales s JOIN inventory_items i ON i.id=s.inventory_item_id JOIN products p ON p.id=i.product_id LEFT JOIN customers c ON c.id=s.customer_id WHERE s.user_id=?';const args:[string,...unknown[]]=[user.id];const m=url.searchParams.get('month');if(m&&m!=='all'){q+=' AND substr(s.sold_on,1,7)=?';args.push(m);}q+=' ORDER BY s.sold_on DESC,s.created_at DESC';const rows=await env.DB.prepare(q).bind(...args).all();return json({sales:rows.results},200,cors(request,env));}
  if(path==='/sales'&&method==='POST'){if(!access(user,true))return json({error:'Read-only način rada.'},403,cors(request,env));const b=await body(request),itemId=text(b.inventory_item_id),qty=Number(b.quantity),sale=cents(b.sale_price),sold=date(b.sold_on)||new Date().toISOString().slice(0,10);if(!itemId||!Number.isInteger(qty)||qty<1||sale<0)return json({error:'Stavka, količina i prodajna cijena su obavezni.'},400,cors(request,env));const customerId=text(b.customer_id)||null;if(customerId&&!await env.DB.prepare('SELECT id FROM customers WHERE id=? AND user_id=?').bind(customerId,user.id).first())return json({error:'Kupac nije pronađen.'},400,cors(request,env));const saleId=id();const results=await env.DB.batch([env.DB.prepare('INSERT INTO sales(id,user_id,inventory_item_id,customer_id,quantity,cost_cents,sale_price_cents,sold_on,note) SELECT ?,?,?,?,?,cost_cents,?,?,? FROM inventory_items WHERE id=? AND user_id=? AND quantity>=?').bind(saleId,user.id,itemId,customerId,qty,sale,sold,text(b.note)||null,itemId,user.id,qty),env.DB.prepare("UPDATE inventory_items SET quantity=quantity-?,status=CASE WHEN quantity-?>0 THEN 'available' ELSE 'reserved' END WHERE id=? AND user_id=? AND quantity>=?").bind(qty,qty,itemId,user.id,qty)]);if(!results[0].meta.changes)return json({error:'Nema dovoljno dostupne količine.'},409,cors(request,env));return json({id:saleId},201,cors(request,env));}
  const saleMatch=path.match(/^\/sales\/([^/]+)$/);if(saleMatch&&method==='DELETE'){if(!access(user,true))return json({error:'Read-only način rada.'},403,cors(request,env));const saleId=saleMatch[1];const results=await env.DB.batch([env.DB.prepare("UPDATE inventory_items SET quantity=quantity+(SELECT quantity FROM sales WHERE id=? AND user_id=?),status='available' WHERE id=(SELECT inventory_item_id FROM sales WHERE id=? AND user_id=?) AND user_id=?").bind(saleId,user.id,saleId,user.id,user.id),env.DB.prepare('DELETE FROM sales WHERE id=? AND user_id=?').bind(saleId,user.id)]);if(!results[1].meta.changes)return json({error:'Prodaja nije pronađena.'},404,cors(request,env));return json({ok:true},200,cors(request,env));}
  return json({error:'Ruta nije pronađena.'},404,cors(request,env));
}
export default { async fetch(request:Request,env:Env) { try{return await handle(request,env);}catch(error){console.error(JSON.stringify({error:String(error)}));return json({error:'Neočekivana greška poslužitelja.'},500,cors(request,env));} } };
